name: iced26
description: "Aplicación para el congreso ICED26."
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ^3.11.4
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
flutter:
  uses-material-design: true
  assets:
    - assets/data/app_data.json
    - assets/brand/
    - assets/brand/iconApp/
flutter_icons:
  # Añadimos el logo como icono de la app.
  android: true
  ios: true
  image_path: "assets/data/brand/logo_iced26_new2-1-1024x628.png"
