name: iced26
description: "Aplicación para el congreso ICED26."
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ^3.11.4
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.9
  url_launcher: ^6.3.2
  google_fonts: ^8.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
flutter:
  uses-material-design: true
  assets:
    - assets/data/app_data.json
    - assets/brand/
    - assets/brand/iconApp/
flutter_icons:
  # Añadimos el logo como icono de la app.
  android: true
  ios: true
  image_path: "assets/data/brand/logo_iced26_new2-1-1024x628.png"
analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
linter:
  rules:
    - avoid_dynamic_calls
    - always_declare_return_types
    - prefer_final_locals
    - avoid_unused_parameters
    - unnecessary_this
    - use_super_parameters
    - camel_case_types