name: iced26
description: "Aplicación para el congreso ICED26."
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ^3.11.4
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.9
  collection: ^1.19.1
  url_launcher: ^6.3.2
  google_fonts: ^8.0.2
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  drift: ^2.16.0
  sqlite3_flutter_libs: ^0.5.21
  path_provider: ^2.1.2
  path: ^1.9.0
  logger: ^2.7.0
  flutter_svg: ^2.2.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  riverpod_generator: ^2.4.0
  drift_dev: ^2.16.0
  build_runner: ^2.4.8
flutter:
  uses-material-design: true
  assets:
    - assets/data/app_data.json
    - assets/brand/
    - assets/brand/iconApp/
flutter_icons:
  # Añadimos el logo como icono de la app.
  android: true
  ios: true
  image_path: "assets/data/brand/logo_iced26_new2-1-1024x628.png"
analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
linter:
  rules:
    - avoid_dynamic_calls
    - always_declare_return_types
    - prefer_final_locals
    - avoid_unused_parameters
    - unnecessary_this
    - use_super_parameters
    - camel_case_types
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - avoid_print
    - prefer_single_quotes
    - sort_constructors_first
    - directives_ordering
    - require_trailing_commas
    - avoid_empty_else
    - unnecessary_lambdas
    - prefer_final_fields
    - avoid_redundant_argument_values